### ISSUE TITLE
Income tax (link/unlinked) VS land Tax or both?

### ISSUE THREAD

**Issue by WilliamMaber** [ppuk/Policies#7]
please look at these and see if there's an issue
plz look at 
1. [Implement A Land Value Tax](https://github.com/ppuk/Policies/blob/5280b06a13199dc30697152428d78e1196d8de27/Economy/Implement%20A%20Land%20Value%20Tax.md)

2. [Fair Tax Brackets](https://github.com/ppuk/Policies/blob/5280b06a13199dc30697152428d78e1196d8de27/Welfare%20And%20Work/Fair%20Tax%20Brackets.md)

then update remove one 
then maybe update
[Merge National Insurance And Income Tax](https://github.com/ppuk/Policies/blob/5280b06a13199dc30697152428d78e1196d8de27/Welfare%20And%20Work/Fair%20Tax%20Brackets.md)

**Comment by WilliamMaber** [comment]
and if we are doing income tax we should look at NIT

**Comment by Topperfalkon** [comment]
I don't think the two are necessarily in conflict, but a broader rethink of tax policy is probably not a bad idea.

**Comment by WilliamMaber** [comment]
that are in Direct conflict one talking about reforming income tax and the other is taking about removing it and replacing it with a land value tax. 

what does the party want to do replace or reform it.

**Comment by Topperfalkon** [comment]
It doesn't actually suggest removing income tax for LVT, though that might be an eventual resolution.

**Comment by WilliamMaber** [comment]
Oh my bad

**Comment by Topperfalkon** [comment]
No worries!
